name: Github conditional flow

on:
  push

jobs:
  job1-display_output:
    name: display a file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: job1-Display the output of the file
        run: |
          cat sample.txt
        shell: bash
        
  conditional_job_success:
    name: Conditional Job for Success
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Display the output
        run: echo "This job is running since previous job has executed successfully."

  conditional_job_failure:
    name: Conditional Job for Failure
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Display the output
        run: echo "This job is running since previous job has failed."
